plugins {
    id 'java-library'
    id 'signing'
    id 'com.vanniktech.maven.publish' version '0.37.0'
}

group = 'com.restonic4.bloom'
version = '1.0.0'

repositories {
    mavenCentral()
}

dependencies { }

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

signing {
    useGpgCmd()
}

mavenPublishing {
    publishToMavenCentral(true)
    signAllPublications()

    coordinates(
            project.group.toString(),
            'events',
            project.version.toString()
    )

    pom {
        name = 'BloomEvents'
        description = 'Event system extracted from the Bloom game engine.'
        url = 'https://github.com/restonic4/BloomEvents'

        licenses {
            license {
                name = 'MIT License'
                url = 'https://opensource.org/license/mit/'
                distribution = 'https://opensource.org/license/mit/'
            }
        }

        developers {
            developer {
                id = 'restonic4'
                name = 'restonic4'
                url = 'https://github.com/restonic4'
            }
        }

        scm {
            connection = 'scm:git:git://github.com/restonic4/BloomEvents.git'
            developerConnection = 'scm:git:ssh://git@github.com/restonic4/BloomEvents.git'
            url = 'https://github.com/restonic4/BloomEvents'
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.compilerArgs += ['-proc:none']
}